import type { QuestionDraft } from "./types";

// Text-only Hungarian party trivia; review status is tracked centrally.
export const animalsQuestions: QuestionDraft[] = [
  [
    1,
    "easy",
    "Melyik állat fekete-fehér csíkos?",
    "Zebra",
    "Zsiráf",
    "Oroszlán",
    "Víziló",
  ],
  [
    2,
    "easy",
    "Hány lába van egy kifejlett rovarnak?",
    "Hat",
    "Négy",
    "Nyolc",
    "Tíz",
  ],
  [
    3,
    "easy",
    "Melyik állat készít mézet?",
    "Mézelő méh",
    "Hangya",
    "Pillangó",
    "Szitakötő",
  ],
  [
    4,
    "normal",
    "Melyik csoportba tartoznak a delfinek?",
    "Emlősök",
    "Halak",
    "Hüllők",
    "Kétéltűek",
  ],
  [
    5,
    "normal",
    "Melyik a legnagyobb ma élő állatfaj?",
    "Kék bálna",
    "Afrikai elefánt",
    "Zsiráf",
    "Óriáskalmár",
  ],
  [
    6,
    "normal",
    "Melyik emlős képes aktív repülésre?",
    "Denevér",
    "Repülőmókus",
    "Koala",
    "Lajhár",
  ],
  [
    7,
    "normal",
    "Hány szíve van egy polipnak?",
    "Három",
    "Egy",
    "Kettő",
    "Négy",
  ],
  [
    8,
    "normal",
    "Melyik madár tud hátrafelé is repülni?",
    "Kolibri",
    "Strucc",
    "Pingvin",
    "Albatrosz",
  ],
  [
    9,
    "normal",
    "Melyik emlős rak tojást?",
    "Kacsacsőrű emlős",
    "Delfin",
    "Vidra",
    "Hód",
  ],
  [
    10,
    "normal",
    "Melyik élőhelyen él természetesen a császárpingvin?",
    "Antarktisz",
    "Szahara",
    "Amazonas-medence",
    "Himalája",
  ],
  [
    11,
    "easy",
    "Melyik állatnak van ormánya?",
    "Elefánt",
    "Orrszarvú",
    "Víziló",
    "Bölény",
    "Az elefánt ormánya megnyúlt orr és felső ajak.",
  ],
  [
    12,
    "easy",
    "Melyik állat hordja kicsinyét jellegzetesen az erszényében?",
    "Kenguru",
    "Zebra",
    "Vidra",
    "Róka",
    "A kenguru az erszényes emlősök közé tartozik.",
  ],
  [
    13,
    "easy",
    "Melyik madár tartozik a röpképtelen fajok közé?",
    "Strucc",
    "Gólya",
    "Sólyom",
    "Fecske",
    "A strucc futáshoz alkalmazkodott, nem képes repülni.",
  ],
  [
    14,
    "easy",
    "Melyik állat fejlődésének egyik állapota az ebihal?",
    "Béka",
    "Gyík",
    "Kígyó",
    "Teknős",
    "Az ebihal a békák vízben élő lárvája.",
  ],
  [
    15,
    "easy",
    "Melyik állat épít gátat ágakból?",
    "Hód",
    "Mókus",
    "Borz",
    "Vakond",
    "A hódok gátjai segítenek megfelelő vízszintet fenntartani.",
  ],
  [
    16,
    "normal",
    "Melyik csoportba tartozik a krokodil?",
    "Hüllők",
    "Emlősök",
    "Kétéltűek",
    "Halak",
    "A krokodil hüllő, nem kétéltű.",
  ],
  [
    17,
    "normal",
    "Melyik állat fő tápláléka a bambusz?",
    "Óriáspanda",
    "Koala",
    "Lajhár",
    "Mosómedve",
    "Az óriáspanda étrendjének túlnyomó részét bambusz alkotja.",
  ],
  [
    18,
    "normal",
    "Melyik állatfaj hímje hordozza a fejlődő utódokat a költőtáskájában?",
    "Csikóhal",
    "Aranyhal",
    "Bohóchal",
    "Harcsa",
    "A csikóhalaknál a nőstény a hím költőtáskájába helyezi az ikrákat.",
  ],
  [
    19,
    "normal",
    "Milyen táplálékot szűrnek ki a kék bálnák főként a vízből?",
    "Krillt",
    "Moszatot",
    "Medúzát",
    "Cápát",
    "A kék bálnák apró rákokat, elsősorban krillt fogyasztanak.",
  ],
  [
    20,
    "normal",
    "Milyen állatok társas kolóniájában él királynő, dolgozó és here?",
    "Mézelő méhek",
    "Katicabogarak",
    "Szitakötők",
    "Szöcskék",
    "A méhcsaládban elkülönülnek a szaporodási és a munkavégzési szerepek.",
  ],
  [
    21,
    "normal",
    "Melyik állatnak van tüskés, összegömbölyíthető teste?",
    "Sün",
    "Borz",
    "Vidra",
    "Görény",
    "A sün veszély esetén összegömbölyödve védi a puha hasát.",
  ],
  [
    22,
    "hard",
    "Melyik anyag alkotja az ízeltlábúak külső vázának fontos részét?",
    "Kitin",
    "Cellulóz",
    "Keményítő",
    "Kollagén",
    "A kitin az ízeltlábúak külső vázának egyik szerkezeti anyaga.",
  ],
  [
    23,
    "hard",
    "Melyik állat tartozik a puhatestűek közé?",
    "Tintahal",
    "Medúza",
    "Tengeri csillag",
    "Homár",
    "A tintahal a puhatestűek fejlábú csoportjába tartozik.",
  ],
  [
    24,
    "hard",
    "Melyik madár képes más madarak hangját és környezeti zajokat utánozni?",
    "Lantfarkú madár",
    "Emu",
    "Kiwi",
    "Kazuár",
    "A lantfarkú madár összetett hangutánzásáról ismert.",
  ],
  [
    25,
    "hard",
    "Melyik állat a legnagyobb ma élő főemlős?",
    "Gorilla",
    "Orangután",
    "Csimpánz",
    "Gibbon",
    "A gorillák testtömege a ma élő főemlősök között a legnagyobb.",
  ],
  [
    26,
    "hard",
    "Melyik állat tájékozódik jellegzetesen visszaverődő ultrahangokkal?",
    "Denevér",
    "Bagoly",
    "Sün",
    "Vakond",
    "Számos denevérfaj a kibocsátott ultrahang visszhangjával érzékeli környezetét.",
  ],
];
