import type { QuestionDraft } from "./types";

// Text-only Hungarian party trivia; review status is tracked centrally.
export const cultureQuestions: QuestionDraft[] = [
  [
    1,
    "easy",
    "Mi a neve a Disney híres rajzolt egérfigurájának?",
    "Mickey egér",
    "Donald kacsa",
    "Goofy",
    "Pluto",
  ],
  [
    2,
    "easy",
    "Melyik képregényhős civil neve Bruce Wayne?",
    "Batman",
    "Superman",
    "Pókember",
    "Vasember",
  ],
  [
    3,
    "easy",
    "Milyen színű a Törpök rajzfilmsorozat szereplőinek jellegzetes bőre?",
    "Kék",
    "Zöld",
    "Lila",
    "Sárga",
  ],
  [
    4,
    "normal",
    "Ki írta A hobbit című regényt?",
    "J. R. R. Tolkien",
    "C. S. Lewis",
    "J. K. Rowling",
    "George Orwell",
  ],
  [
    5,
    "normal",
    "Mi Sherlock Holmes londoni címének házszáma?",
    "221B",
    "42",
    "10",
    "13A",
  ],
  [
    6,
    "normal",
    "Melyik képregényhős használja a Mjölnir nevű kalapácsot?",
    "Thor",
    "Hulk",
    "Flash",
    "Aquaman",
  ],
  [
    7,
    "normal",
    "Melyik országból származik a LEGO?",
    "Dánia",
    "Svédország",
    "Németország",
    "Hollandia",
  ],
  [
    8,
    "hard",
    "Ki írta a Galaxis útikalauz stopposoknak című regényt?",
    "Douglas Adams",
    "Isaac Asimov",
    "Arthur C. Clarke",
    "Ray Bradbury",
  ],
  [
    9,
    "hard",
    "Melyik festő alkotta meg A csillagos éj című képet?",
    "Vincent van Gogh",
    "Claude Monet",
    "Pablo Picasso",
    "Salvador Dalí",
  ],
  [
    10,
    "hard",
    "Melyik regényben szerepel Winston Smith?",
    "1984",
    "Szép új világ",
    "Fahrenheit 451",
    "Állatfarm",
  ],
  [
    11,
    "easy",
    "Melyik mesében veszti el a főhős az üvegcipellőjét?",
    "Hamupipőke",
    "Hófehérke",
    "Csipkerózsika",
    "Aranyhaj",
    "Hamupipőke a bálból sietve távozva hagyja el a cipellőt.",
  ],
  [
    12,
    "easy",
    "Melyik képregényhős jellegzetes eszköze a hálóvető?",
    "Pókember",
    "Batman",
    "Superman",
    "Amerika Kapitány",
    "Pókember hálóval közlekedik és küzd.",
  ],
  [
    13,
    "easy",
    "Melyik mesebeli alak orra nő meg, amikor hazudik?",
    "Pinokkió",
    "Pán Péter",
    "Aladdin",
    "Bambi",
    "Pinokkió fabábu, akinek az orra elárulhatja a hazugságot.",
  ],
  [
    14,
    "easy",
    "Mi Micimackó kedvenc csemegéje?",
    "Méz",
    "Répa",
    "Sajt",
    "Mogyoró",
    "Milne meséinek medvéje különösen kedveli a mézet.",
  ],
  [
    15,
    "easy",
    "Melyik szuperhős civil neve Clark Kent?",
    "Superman",
    "Batman",
    "Flash",
    "Aquaman",
    "Superman újságíróként Clark Kent nevét használja.",
  ],
  [
    16,
    "normal",
    "Ki festette a Mona Lisát?",
    "Leonardo da Vinci",
    "Michelangelo",
    "Raffaello",
    "Sandro Botticelli",
    "A Mona Lisa Leonardo da Vinci portréja.",
  ],
  [
    17,
    "normal",
    "Ki írta A kis herceg című művet?",
    "Antoine de Saint-Exupéry",
    "Jules Verne",
    "Victor Hugo",
    "Albert Camus",
    "Saint-Exupéry pilóta és író volt.",
  ],
  [
    18,
    "normal",
    "Melyik regényben szerepel Maugli?",
    "A dzsungel könyve",
    "Tarzan",
    "Robinson Crusoe",
    "Gulliver utazásai",
    "Maugli Rudyard Kipling történeteinek farkasok közt nevelkedő gyereke.",
  ],
  [
    19,
    "normal",
    "Melyik ország hagyományos ruhadarabja a kimono?",
    "Japán",
    "India",
    "Marokkó",
    "Mexikó",
    "A kimono hagyományos japán viselet.",
  ],
  [
    20,
    "normal",
    "Melyik mitológia főistene Zeusz?",
    "Görög",
    "Skandináv",
    "Egyiptomi",
    "Kelta",
    "Zeusz az ókori görög istenvilág központi alakja.",
  ],
  [
    21,
    "normal",
    "Melyik színházi műfajban jut kiemelt szerep az éneknek és zenekari kíséretnek?",
    "Opera",
    "Pantomim",
    "Prózai monodráma",
    "Bábjáték",
    "Az opera énekes színpadi mű, rendszerint zenekari kísérettel.",
  ],
  [
    22,
    "hard",
    "Ki írta az Állatfarm című regényt?",
    "George Orwell",
    "Aldous Huxley",
    "William Golding",
    "Ray Bradbury",
    "Orwell állatmeséje politikai szatíra.",
  ],
  [
    23,
    "hard",
    "Melyik festő műve Az emlékezet állandósága, az olvadó órákkal?",
    "Salvador Dalí",
    "René Magritte",
    "Joan Miró",
    "Pablo Picasso",
    "Dalí szürrealista festményén lágyan elfolyó órák szerepelnek.",
  ],
  [
    24,
    "hard",
    "Melyik ország írója volt Gabriel García Márquez?",
    "Kolumbia",
    "Chile",
    "Mexikó",
    "Peru",
    "García Márquez kolumbiai író, a Száz év magány szerzője.",
  ],
  [
    25,
    "hard",
    "Melyik görög hős jut ki Ariadné fonalával a labirintusból?",
    "Thészeusz",
    "Perseusz",
    "Akhilleusz",
    "Héraklész",
    "Thészeusz a Minótaurosz történetének hőse.",
  ],
  [
    26,
    "hard",
    "Melyik regény főszereplője Jean Valjean?",
    "A nyomorultak",
    "Monte Cristo grófja",
    "A három testőr",
    "Vörös és fekete",
    "Jean Valjean Victor Hugo regényének központi alakja.",
  ],
];
