import type { QuestionDraft } from "./types";

// Text-only Hungarian party trivia; review status is tracked centrally.
export const filmQuestions: QuestionDraft[] = [
  [
    1,
    "easy",
    "Mi a neve a Star Wars zöld, bölcs jedimesterének?",
    "Yoda",
    "Gandalf",
    "Spock",
    "Dobby",
  ],
  [
    2,
    "easy",
    "Melyik filmben szerepel Simba?",
    "Az oroszlánkirály",
    "Shrek",
    "Jégvarázs",
    "Aladdin",
  ],
  [
    3,
    "easy",
    "Mi a neve Harry Potter iskolájának magyarul?",
    "Roxfort",
    "Narnia",
    "Mordor",
    "Gotham",
  ],
  [
    4,
    "normal",
    "Ki rendezte az 1997-es Titanic című filmet?",
    "James Cameron",
    "Steven Spielberg",
    "George Lucas",
    "Christopher Nolan",
  ],
  [
    5,
    "normal",
    "Melyik városban játszódik főként a Jóbarátok?",
    "New York",
    "Los Angeles",
    "Chicago",
    "Seattle",
  ],
  [
    6,
    "normal",
    "Mi a neve A Gyűrűk Ura hobbitjának, aki a gyűrűt viszi?",
    "Frodó",
    "Bilbó",
    "Aragorn",
    "Legolas",
  ],
  [
    7,
    "normal",
    "Melyik filmben szerepel a DeLorean időgép?",
    "Vissza a jövőbe",
    "Jurassic Park",
    "Mátrix",
    "Terminátor",
  ],
  [
    8,
    "hard",
    "Ki rendezte a Chihiro Szellemországban című filmet?",
    "Mijazaki Hajao",
    "Kuroszava Akira",
    "Satoshi Kon",
    "Isao Takahata",
  ],
  [
    9,
    "normal",
    "Melyik színész alakítja Jack Sparrow-t A Karib-tenger kalózaiban?",
    "Johnny Depp",
    "Orlando Bloom",
    "Brad Pitt",
    "Tom Hanks",
  ],
  [
    10,
    "hard",
    "Mi a neve az Alien filmek űrhajójának az első részben?",
    "Nostromo",
    "Enterprise",
    "Millennium Falcon",
    "Discovery",
  ],
  [
    11,
    "easy",
    "Melyik filmben barátkozik össze egy ogre egy beszélő szamárral?",
    "Shrek",
    "Jégkorszak",
    "Némó nyomában",
    "Madagaszkár",
    "Shrek útitársa a beszédes Szamár.",
  ],
  [
    12,
    "easy",
    "Melyik animációs film cowboy játéka Woody?",
    "Toy Story",
    "Fel!",
    "Verdák",
    "L'ecsó",
    "Woody Andy játékainak egyik központi szereplője.",
  ],
  [
    13,
    "easy",
    "Mi Homer Simpson feleségének keresztneve?",
    "Marge",
    "Lisa",
    "Maggie",
    "Patty",
    "Marge Simpson Homer felesége, Lisa és Maggie a lányaik.",
  ],
  [
    14,
    "easy",
    "Melyik filmben találkozhatunk Elsa és Anna testvérpárjával?",
    "Jégvarázs",
    "Aranyhaj és a nagy gubanc",
    "Vaiana",
    "Merida, a bátor",
    "Elsa és Anna Arendelle királyi családjához tartozik.",
  ],
  [
    15,
    "easy",
    "Melyik animációs filmben szerepel Villám McQueen?",
    "Verdák",
    "Repcsik",
    "Robotok",
    "WALL-E",
    "Villám McQueen a Verdák versenyautó-főszereplője.",
  ],
  [
    16,
    "normal",
    "Mi a Némó nyomában főszereplő halainak típusa?",
    "Bohóchal",
    "Aranyhal",
    "Tonhal",
    "Csikóhal",
    "Némó és apja, Pizsi bohóchalak.",
  ],
  [
    17,
    "normal",
    "Melyik filmben működik egy főzni szerető patkány egy párizsi konyhában?",
    "L'ecsó",
    "Zootropolis",
    "Így neveld a sárkányodat",
    "Kung Fu Panda",
    "Remy a L'ecsó konyhaművészetért lelkesedő patkánya.",
  ],
  [
    18,
    "normal",
    "Ki alakítja Forrest Gumpot az 1994-es filmben?",
    "Tom Hanks",
    "Tom Cruise",
    "Robin Williams",
    "Kevin Costner",
    "A címszerepet Tom Hanks játssza.",
  ],
  [
    19,
    "normal",
    "Melyik filmben választhat Neo piros és kék pirula között?",
    "Mátrix",
    "Eredet",
    "Blade Runner",
    "Különvélemény",
    "Morpheus a Mátrixban kínálja fel Neónak a két pirulát.",
  ],
  [
    20,
    "normal",
    "Melyik ország filmiparához kötődik a Bollywood elnevezés?",
    "India",
    "Japán",
    "Dél-Korea",
    "Brazília",
    "Bollywood a mumbai központú, hindi nyelvű filmipar elnevezése.",
  ],
  [
    21,
    "normal",
    "Melyik sorozatban dolgozik Walter White kémiatanárként a történet elején?",
    "Breaking Bad",
    "Dexter",
    "A mentalista",
    "Doktor House",
    "Walter White kémiatanárból válik bűnözővé.",
  ],
  [
    22,
    "hard",
    "Ki rendezte a Jurassic Park 1993-as filmjét?",
    "Steven Spielberg",
    "Ridley Scott",
    "James Cameron",
    "Peter Jackson",
    "Spielberg rendezte a dinoszauruszparkban játszódó első filmet.",
  ],
  [
    23,
    "hard",
    "Milyen technikával készülnek a klasszikus Wallace és Gromit filmek?",
    "Stop-motion",
    "Élő szereplős felvétel",
    "Kézzel rajzolt animáció",
    "Mozgásrögzítéses animáció",
    "A figurákat kis lépésekben mozgatva, képkockánként fényképezik.",
  ],
  [
    24,
    "hard",
    "Melyik film zenéjét szerezte Ennio Morricone?",
    "A Jó, a Rossz és a Csúf",
    "Titanic",
    "Star Wars: Egy új remény",
    "A Gyűrűk Ura: A Gyűrű Szövetsége",
    "Morricone Sergio Leone westernjéhez írta a jellegzetes filmzenét.",
  ],
  [
    25,
    "hard",
    "Melyik rendezőhöz kötődik az Eredet című 2010-es film?",
    "Christopher Nolan",
    "David Fincher",
    "Quentin Tarantino",
    "Wes Anderson",
    "Nolan írta és rendezte az álomrétegekkel játszó filmet.",
  ],
  [
    26,
    "hard",
    "Melyik filmben nyomoz Clarice Starling Hannibal Lecter segítségével?",
    "A bárányok hallgatnak",
    "Hetedik",
    "Zodiákus",
    "Viharsziget",
    "Clarice Starling a sorozatgyilkos Lecterrel beszélget a nyomozás során.",
  ],
];
