import type { QuestionDraft } from "./types";

// Text-only Hungarian party trivia; review status is tracked centrally.
export const foodQuestions: QuestionDraft[] = [
  [
    1,
    "easy",
    "Melyik gyümölcsből készül a hagyományos vörös- és fehérbor?",
    "Szőlő",
    "Banán",
    "Ananász",
    "Körte",
  ],
  [
    2,
    "easy",
    "Melyik ország konyhájához kötődik a pizza?",
    "Olaszország",
    "Japán",
    "India",
    "Svédország",
  ],
  [
    3,
    "easy",
    "Melyik összetevő adja a csokoládé jellegzetes alapját?",
    "Kakaó",
    "Kávé",
    "Vanília",
    "Fahéj",
  ],
  [
    4,
    "normal",
    "Miből készül a hagyományos tofu?",
    "Szójababból",
    "Burgonyából",
    "Tejből",
    "Rizsből",
  ],
  [
    5,
    "normal",
    "Melyik gabonából készül a kuszkusz hagyományosan?",
    "Durumbúzából",
    "Rozsból",
    "Rizsből",
    "Zabból",
  ],
  [
    6,
    "normal",
    "Melyik étel fő összetevője a csicseriborsó?",
    "Hummusz",
    "Pesto",
    "Guacamole",
    "Tzatziki",
  ],
  [
    7,
    "normal",
    "Miből készül az őrölt fűszerpaprika?",
    "Szárított paprikatermésből",
    "Szárított hagymalevélből",
    "Őrölt kávébabból",
    "Reszelt gyömbérgyökérből",
  ],
  [
    8,
    "hard",
    "Melyik virág bibéjéből készül a sáfrány?",
    "Sáfránykrókusz",
    "Rózsa",
    "Napraforgó",
    "Tulipán",
  ],
  [
    9,
    "hard",
    "Melyik olasz desszert neve jelent szó szerint „főtt tejszínt”?",
    "Panna cotta",
    "Tiramisù",
    "Cannoli",
    "Gelato",
  ],
  [
    10,
    "hard",
    "Melyik francia kék sajtot érlelik hagyományosan a Combalou-hegy barlangjaiban?",
    "Roquefort",
    "Cheddar",
    "Mozzarella",
    "Gouda",
  ],
  [
    11,
    "easy",
    "Melyik alapanyag adja a guacamole jellegzetes alapját?",
    "Avokádó",
    "Csicseriborsó",
    "Padlizsán",
    "Uborka",
    "A guacamole avokádóból készülő mexikói krém.",
  ],
  [
    12,
    "easy",
    "Melyik ital készül pörkölt, őrölt kávészemekből?",
    "Kávé",
    "Tea",
    "Kakaó",
    "Limonádé",
    "A kávéitalhoz a pörkölt magokból vizet használva oldanak ki ízanyagokat.",
  ],
  [
    13,
    "easy",
    "Melyik gyümölcsöt szárítják mazsolává?",
    "Szőlő",
    "Szilva",
    "Sárgabarack",
    "Meggy",
    "A mazsola szárított szőlőszem.",
  ],
  [
    14,
    "easy",
    "Melyik zöldségből készül hagyományosan a savanyú káposzta?",
    "Fejes káposzta",
    "Kelbimbó",
    "Karfiol",
    "Brokkoli",
    "A savanyú káposztát sózott fejes káposzta erjesztésével készítik.",
  ],
  [
    15,
    "easy",
    "Melyik ország konyhájához kötődik a sushi?",
    "Japán",
    "Thaiföld",
    "India",
    "Vietnam",
    "A sushi ecetes rizsre épülő japán étel, és nem mindig tartalmaz nyers halat.",
  ],
  [
    16,
    "normal",
    "Melyik növény levele a klasszikus genovai pesto fő fűszere?",
    "Bazsalikom",
    "Petrezselyem",
    "Koriander",
    "Menta",
    "A pesto alla genovese jellegzetes zöld ízét a bazsalikom adja.",
  ],
  [
    17,
    "normal",
    "Melyik összetevő kelti meg a hagyományos kenyértésztát?",
    "Élesztő",
    "Só",
    "Olaj",
    "Ecet",
    "Az élesztő erjedéskor keletkező szén-dioxidja lazítja a tésztát.",
  ],
  [
    18,
    "normal",
    "Melyik országhoz kötődik a paella?",
    "Spanyolország",
    "Portugália",
    "Franciaország",
    "Görögország",
    "A paella valenciai eredetű rizsétel.",
  ],
  [
    19,
    "normal",
    "Milyen tejből készül hagyományosan az eredetvédett feta?",
    "Juhtejből, esetleg kecsketejjel",
    "Csak tehéntejből",
    "Bivalytejből",
    "Kancatejből",
    "A görög feta juhtejből készül, legfeljebb 30 százalék kecsketej hozzáadásával.",
  ],
  [
    20,
    "normal",
    "Melyik növény adja a fahéjfűszert?",
    "Fahéjfa kérge",
    "Vanília termése",
    "Gyömbér gyöktörzse",
    "Szegfűszeg virágrügye",
    "A fahéj bizonyos Cinnamomum-fajok szárított belső kérge.",
  ],
  [
    21,
    "normal",
    "Melyik élőlénycsoport indítja el a tej joghurttá erjedését?",
    "Baktériumok",
    "Penészgombák",
    "Algák",
    "Élesztőgombák",
    "A joghurt készítéséhez tejsavtermelő baktériumokat használnak.",
  ],
  [
    22,
    "hard",
    "Miből készül a japán miso alapja?",
    "Erjesztett szójababból",
    "Nyers burgonyából",
    "Szárított almából",
    "Pörkölt kakaóbabból",
    "A miso rendszerint szójabab és gabona erjesztésével készülő paszta.",
  ],
  [
    23,
    "hard",
    "Melyik fűszer sárga színanyaga a kurkumin?",
    "Kurkuma",
    "Fahéj",
    "Szegfűbors",
    "Szerecsendió",
    "A kurkumin a kurkuma jellegzetes sárga pigmentje.",
  ],
  [
    24,
    "hard",
    "Mi a tahini fő összetevője?",
    "Szezámmag",
    "Napraforgómag",
    "Mogyoró",
    "Mandula",
    "A tahini őrölt szezámmagból készülő paszta.",
  ],
  [
    25,
    "hard",
    "Melyik rizsfajtát használják gyakran olasz rizottóhoz?",
    "Arborio",
    "Basmati",
    "Jázminrizs",
    "Vadrizs",
    "Az Arborio keményítőtartalma segít a rizottó krémes állagának kialakításában.",
  ],
  [
    26,
    "hard",
    "Melyik összetevő adja a hagyományos béchamel alapját a vaj és liszt mellett?",
    "Tej",
    "Paradicsomlé",
    "Tojásfehérje",
    "Olívaolaj",
    "A béchamel tejjel felöntött világos rántásból készülő mártás.",
  ],
];
