import type { QuestionDraft } from "./types";

// Text-only Hungarian party trivia; review status is tracked centrally.
export const gamesQuestions: QuestionDraft[] = [
  [
    1,
    "easy",
    "Melyik játék főhőse egy bajuszos, piros sapkás vízvezeték-szerelő?",
    "Super Mario",
    "Sonic",
    "Pac-Man",
    "Kirby",
  ],
  [
    2,
    "easy",
    "Melyik játékban építhetsz blokkokból egy procedurális világban?",
    "Minecraft",
    "Tetris",
    "FIFA",
    "Street Fighter",
  ],
  [
    3,
    "easy",
    "Melyik játékban kell leeső alakzatokból sorokat kirakni?",
    "Tetris",
    "Doom",
    "Portal",
    "Civilization",
  ],
  [
    4,
    "normal",
    "Ki a The Legend of Zelda játékok legtöbb részének játszható hőse?",
    "Link",
    "Zelda",
    "Ganondorf",
    "Epona",
  ],
  [
    5,
    "normal",
    "Melyik cég alkotta meg a Pokémon első videojátékait?",
    "Game Freak",
    "Valve",
    "Bungie",
    "id Software",
  ],
  [
    6,
    "normal",
    "Melyik játékban van GLaDOS nevű mesterséges intelligencia?",
    "Portal",
    "Half-Life",
    "Halo",
    "BioShock",
  ],
  [
    7,
    "normal",
    "Melyik sorozatban szerepel a Master Chief?",
    "Halo",
    "Mass Effect",
    "Fallout",
    "Metal Gear",
  ],
  [
    8,
    "hard",
    "Ki fejlesztette eredetileg egyedül a Stardew Valley játékot?",
    "ConcernedApe",
    "Shigeru Miyamoto",
    "Hideo Kojima",
    "Gabe Newell",
  ],
  [
    9,
    "hard",
    "Mi a Hades című 2020-as játék főhősének neve?",
    "Zagreusz",
    "Kratosz",
    "Atreusz",
    "Hermész",
  ],
  [
    10,
    "hard",
    "Melyik cég készítette az eredeti 1993-as Doom játékot?",
    "id Software",
    "Valve",
    "Blizzard",
    "Rare",
  ],
  [
    11,
    "easy",
    "Melyik játék sárga főhőse eszik pontokat egy labirintusban?",
    "Pac-Man",
    "Sonic",
    "Crash Bandicoot",
    "Donkey Kong",
    "Pac-Man a labirintusban pontokat gyűjt, miközben szellemek kergetik.",
  ],
  [
    12,
    "easy",
    "Melyik konzolcsalád tartozik a Sonyhoz?",
    "PlayStation",
    "Xbox",
    "Switch",
    "Dreamcast",
    "A PlayStation a Sony konzolmárkája.",
  ],
  [
    13,
    "easy",
    "Melyik társasjátékban szerepelnek utcák, házak és szállodák?",
    "Monopoly",
    "Scrabble",
    "Cluedo",
    "Malom",
    "A Monopoly játékosai ingatlanokat vásárolnak és fejlesztenek.",
  ],
  [
    14,
    "easy",
    "Milyen színű a legismertebb Sonic-karakter?",
    "Kék",
    "Piros",
    "Zöld",
    "Sárga",
    "Sonic jellegzetes kék sündisznó.",
  ],
  [
    15,
    "easy",
    "Melyik játékban lehet betűlapkákból szavakat alkotni?",
    "Scrabble",
    "Cluedo",
    "Risk",
    "Jenga",
    "A Scrabble tábláján keresztbe kapcsolódó szavakat raknak ki.",
  ],
  [
    16,
    "normal",
    "Melyik vállalat konzolcsaládja az Xbox?",
    "Microsoft",
    "Nintendo",
    "Sega",
    "Atari",
    "Az Xbox a Microsoft videojátékos márkája.",
  ],
  [
    17,
    "normal",
    "Mi a neve a Minecraft robbanó, zöld ellenfelének?",
    "Creeper",
    "Enderman",
    "Ghast",
    "Blaze",
    "A creeper a közelébe érő játékos mellett felrobbanhat.",
  ],
  [
    18,
    "normal",
    "Melyik játékcsalád vámpírvadásza a Belmont család?",
    "Castlevania",
    "Metroid",
    "Mega Man",
    "Final Fantasy",
    "A Castlevania sorozat több részében a Belmontok küzdenek Drakula ellen.",
  ],
  [
    19,
    "normal",
    "Melyik társasjátékban kell egy gyilkosság tettesét, eszközét és helyszínét kitalálni?",
    "Cluedo",
    "Monopoly",
    "Carcassonne",
    "Dixit",
    "A Cluedo nyomozói három rejtett adatot próbálnak kikövetkeztetni.",
  ],
  [
    20,
    "normal",
    "Melyik videojáték-sorozatban szerepel Lara Croft?",
    "Tomb Raider",
    "Uncharted",
    "Prince of Persia",
    "Assassin's Creed",
    "Lara Croft a Tomb Raider kalandjátékok főhőse.",
  ],
  [
    21,
    "normal",
    "Melyik játékban versenyeznek gokarttal a Nintendo ismert karakterei?",
    "Mario Kart",
    "Gran Turismo",
    "Forza Motorsport",
    "Need for Speed",
    "A Mario Kart versenyzői közé Mario és több Nintendo-karakter tartozik.",
  ],
  [
    22,
    "hard",
    "Melyik sorozat főhőse Samus Aran?",
    "Metroid",
    "Bayonetta",
    "Mass Effect",
    "Horizon",
    "Samus Aran a Metroid sorozat páncélos fejvadásza.",
  ],
  [
    23,
    "hard",
    "Melyik játék fejlesztője a Supergiant Games?",
    "Bastion",
    "Hollow Knight",
    "Celeste",
    "Dead Cells",
    "A Bastion a Supergiant Games első megjelent játéka.",
  ],
  [
    24,
    "hard",
    "Melyik játékban van Rapture nevű víz alatti város?",
    "BioShock",
    "Fallout",
    "Deus Ex",
    "Dishonored",
    "Az első BioShock történetének helyszíne Rapture.",
  ],
  [
    25,
    "hard",
    "Melyik játékcsaládban szerepel a Vault Boy nevű szőke kabalafigura?",
    "Fallout",
    "Borderlands",
    "Half-Life",
    "The Elder Scrolls",
    "A Vault Boy a Fallout jellegzetes vállalati kabalafigurája.",
  ],
  [
    26,
    "hard",
    "Melyik játékban ismert frakció a Terran, a Zerg és a Protoss?",
    "StarCraft",
    "Warcraft",
    "Age of Empires",
    "Command & Conquer",
    "A StarCraft három játszható faját ezek a frakciók adják.",
  ],
];
