import type { QuestionDraft } from "./types";

// Text-only Hungarian party trivia; review status is tracked centrally.
export const geographyQuestions: QuestionDraft[] = [
  [
    1,
    "easy",
    "Melyik ország fővárosa Párizs?",
    "Franciaország",
    "Olaszország",
    "Spanyolország",
    "Belgium",
  ],
  [
    2,
    "easy",
    "Melyik kontinensen fekszik Egyiptom területének nagy része?",
    "Afrika",
    "Európa",
    "Dél-Amerika",
    "Ausztrália",
  ],
  [
    3,
    "easy",
    "Melyik óceán a legnagyobb?",
    "Csendes-óceán",
    "Atlanti-óceán",
    "Indiai-óceán",
    "Jeges-tenger",
  ],
  [
    4,
    "normal",
    "Melyik ország fővárosa Canberra?",
    "Ausztrália",
    "Új-Zéland",
    "Kanada",
    "Dél-Afrika",
  ],
  [
    5,
    "normal",
    "Melyik folyó szeli át Londont?",
    "Temze",
    "Szajna",
    "Rajna",
    "Tiberis",
  ],
  [
    6,
    "normal",
    "Melyik hegységben található a Mount Everest?",
    "Himalája",
    "Andok",
    "Alpok",
    "Kaukázus",
  ],
  [
    7,
    "normal",
    "Melyik országban található Machu Picchu?",
    "Peru",
    "Mexikó",
    "Brazília",
    "Chile",
  ],
  [
    8,
    "hard",
    "Melyik szoros választja el Spanyolországot Marokkótól?",
    "Gibraltári-szoros",
    "Bering-szoros",
    "Malaka-szoros",
    "Hormuzi-szoros",
  ],
  [
    9,
    "hard",
    "Melyik tó osztozik Peru és Bolívia területén?",
    "Titicaca",
    "Balaton",
    "Bajkál",
    "Viktória-tó",
  ],
  [
    10,
    "hard",
    "Melyik ország veszi teljesen körül Lesothót?",
    "Dél-Afrika",
    "Kenya",
    "Egyiptom",
    "Namíbia",
  ],
  [
    11,
    "easy",
    "Melyik ország térképét szokták csizmához hasonlítani?",
    "Olaszország",
    "Görögország",
    "Portugália",
    "Norvégia",
    "Az Appennini-félsziget jellegzetes alakja egy csizmára emlékeztet.",
  ],
  [
    12,
    "easy",
    "Melyik földrészen található az Amazonas-medence?",
    "Dél-Amerika",
    "Afrika",
    "Ázsia",
    "Ausztrália",
    "Az Amazonas vízgyűjtője Dél-Amerika északi részén terül el.",
  ],
  [
    13,
    "easy",
    "Melyik országban található az Eiffel-torony?",
    "Franciaország",
    "Belgium",
    "Németország",
    "Svájc",
    "Az Eiffel-torony Párizs egyik legismertebb építménye.",
  ],
  [
    14,
    "easy",
    "Melyik természetes jelenség hozta létre a Grand Canyont?",
    "Folyóvízi erózió",
    "Vulkánkitörés",
    "Meteoritbecsapódás",
    "Korallok építkezése",
    "A Colorado folyó és mellékfolyói mélyítették a kanyont.",
  ],
  [
    15,
    "easy",
    "Melyik sivatag húzódik Észak-Afrika nagy részén?",
    "Szahara",
    "Góbi",
    "Atacama",
    "Kalahári",
    "A Szahara Észak-Afrika kiterjedt forró sivataga.",
  ],
  [
    16,
    "normal",
    "Melyik országban található a Fuji-hegy?",
    "Japán",
    "Kína",
    "Dél-Korea",
    "Vietnam",
    "A Fuji Japán legmagasabb hegye és egyben vulkán.",
  ],
  [
    17,
    "normal",
    "Melyik tenger választja el Európát Észak-Afrikától?",
    "Földközi-tenger",
    "Balti-tenger",
    "Vörös-tenger",
    "Arab-tenger",
    "A Földközi-tenger partvidékén Európa, Afrika és Ázsia találkozik.",
  ],
  [
    18,
    "normal",
    "Melyik ország területén található Petra sziklába vájt romvárosa?",
    "Jordánia",
    "Egyiptom",
    "Libanon",
    "Irak",
    "Petra a nabateusok egykori központja, a mai Jordániában.",
  ],
  [
    19,
    "normal",
    "Melyik ország nevezetes a fjordjairól az alábbiak közül?",
    "Norvégia",
    "Magyarország",
    "Belgium",
    "Lengyelország",
    "A fjordok jég által mélyített, tengerrel elárasztott völgyek.",
  ],
  [
    20,
    "normal",
    "Melyik hegység húzódik Dél-Amerika nyugati peremén?",
    "Andok",
    "Sziklás-hegység",
    "Urál",
    "Atlasz",
    "Az Andok a kontinens csendes-óceáni oldalát követi.",
  ],
  [
    21,
    "normal",
    "Melyik kontinensen található a Kilimandzsáró?",
    "Afrika",
    "Ázsia",
    "Európa",
    "Dél-Amerika",
    "A Kilimandzsáró Tanzániában emelkedik.",
  ],
  [
    22,
    "hard",
    "Melyik pireneusi törpeállam fekszik Franciaország és Spanyolország között?",
    "Andorra",
    "Monaco",
    "San Marino",
    "Liechtenstein",
    "Andorra a Pireneusokban, Spanyolország és Franciaország között fekszik.",
  ],
  [
    23,
    "hard",
    "Melyik tengerhez kapcsolja a Szuezi-csatorna a Földközi-tengert?",
    "Vörös-tenger",
    "Fekete-tenger",
    "Arab-tenger",
    "Kaszpi-tenger",
    "A csatorna a Földközi- és a Vörös-tenger közötti hajóút.",
  ],
  [
    24,
    "hard",
    "Melyik ország része Grönland autonóm területként?",
    "Dánia",
    "Norvégia",
    "Kanada",
    "Izland",
    "Grönland a Dán Királyságon belül széles körű önkormányzattal rendelkezik.",
  ],
  [
    25,
    "hard",
    "Melyik ország fővárosa Wellington?",
    "Új-Zéland",
    "Ausztrália",
    "Fidzsi",
    "Szamoa",
    "Wellington Új-Zéland Északi-szigetének déli részén fekszik.",
  ],
  [
    26,
    "hard",
    "Melyik ország fővárosa Reykjavík?",
    "Izland",
    "Norvégia",
    "Dánia",
    "Finnország",
    "Reykjavík Izland fővárosa és legnagyobb városa.",
  ],
];
