import type { QuestionDraft } from "./types";

// Text-only Hungarian party trivia; review status is tracked centrally.
export const historyQuestions: QuestionDraft[] = [
  [
    1,
    "easy",
    "Melyik civilizáció építette a gízai piramisokat?",
    "Ókori egyiptomi",
    "Ókori görög",
    "Római",
    "Viking",
  ],
  [
    2,
    "easy",
    "Melyik évben ért véget a második világháború?",
    "1945",
    "1939",
    "1918",
    "1956",
  ],
  [
    3,
    "easy",
    "Ki volt az első ember a Holdon?",
    "Neil Armstrong",
    "Jurij Gagarin",
    "Buzz Aldrin",
    "John Glenn",
  ],
  [
    4,
    "normal",
    "Melyik évben kezdődött a francia forradalom?",
    "1789",
    "1848",
    "1776",
    "1815",
  ],
  [
    5,
    "normal",
    "Melyik várost temette be a Vezúv i. sz. 79-ben?",
    "Pompeji",
    "Athén",
    "Karthágó",
    "Spárta",
  ],
  [
    6,
    "normal",
    "Melyik országban írták alá a Magna Cartát 1215-ben?",
    "Anglia",
    "Franciaország",
    "Spanyolország",
    "Svédország",
  ],
  [
    7,
    "normal",
    "Ki volt a mongol birodalom alapítója?",
    "Dzsingisz kán",
    "Nagy Sándor",
    "Attila",
    "I. Dareiosz",
  ],
  [
    8,
    "hard",
    "Melyik csatában szenvedett végső vereséget Napóleon 1815-ben?",
    "Waterloo",
    "Austerlitz",
    "Trafalgar",
    "Marathon",
  ],
  [
    9,
    "hard",
    "Melyik évben esett el Konstantinápoly az oszmánok előtt?",
    "1453",
    "1492",
    "1526",
    "1204",
  ],
  [
    10,
    "hard",
    "Ki vezette az első világ körüli hajóút hazatérő szakaszát?",
    "Juan Sebastián Elcano",
    "Kolumbusz Kristóf",
    "Vasco da Gama",
    "James Cook",
  ],
  [
    11,
    "easy",
    "Melyik ókori városban állt a Colosseum?",
    "Róma",
    "Athén",
    "Alexandria",
    "Babilon",
    "A Colosseum Róma hatalmas amfiteátruma.",
  ],
  [
    12,
    "easy",
    "Melyik országhoz kötődik a viking kor hajósainak többsége az alábbiak közül?",
    "Norvégia",
    "Spanyolország",
    "Görögország",
    "Portugália",
    "A vikingek elsősorban a skandináv térségből indultak útjaikra.",
  ],
  [
    13,
    "easy",
    "Milyen anyagra írtak gyakran az ókori Egyiptomban?",
    "Papiruszra",
    "Pergamenre",
    "Selyemre",
    "Agyagtáblára",
    "A papirusznövényből készített lapokat íráshoz használták.",
  ],
  [
    14,
    "easy",
    "Melyik uralkodóhoz kötődik a napkirály elnevezés?",
    "XIV. Lajos",
    "VIII. Henrik",
    "I. Erzsébet",
    "Nagy Péter",
    "A francia XIV. Lajos a Napot használta uralkodói jelképként.",
  ],
  [
    15,
    "easy",
    "Mi választotta el Berlint 1961 és 1989 között?",
    "A berlini fal",
    "A kínai nagy fal",
    "Hadrianus fala",
    "A Maginot-vonal",
    "A fal a város keleti és nyugati részét választotta el.",
  ],
  [
    16,
    "normal",
    "Melyik néphez kötődnek az ókori olimpiai játékok?",
    "Görögök",
    "Föníciaiak",
    "Perzsák",
    "Kelták",
    "Az ókori versenyeket Olümpiában rendezték.",
  ],
  [
    17,
    "normal",
    "Melyik feltaláló neve kapcsolódik az európai könyvnyomtatás elterjedéséhez?",
    "Johannes Gutenberg",
    "James Watt",
    "Thomas Edison",
    "Alfred Nobel",
    "Gutenberg mozgatható fémbetűs nyomtatási eljárása segítette a könyvek terjedését.",
  ],
  [
    18,
    "normal",
    "Melyik országban kezdődött az ipari forradalom?",
    "Nagy-Britannia",
    "Oroszország",
    "Olaszország",
    "Portugália",
    "A gépesített gyáripar először Nagy-Britanniában bontakozott ki.",
  ],
  [
    19,
    "normal",
    "Ki lett Dél-Afrika első fekete elnöke 1994-ben?",
    "Nelson Mandela",
    "Desmond Tutu",
    "Kwame Nkrumah",
    "Patrice Lumumba",
    "Mandela az apartheid utáni első általános választás után lett elnök.",
  ],
  [
    20,
    "normal",
    "Melyik állam adta az Egyesült Államoknak a Szabadság-szobrot?",
    "Franciaország",
    "Nagy-Britannia",
    "Spanyolország",
    "Olaszország",
    "A szobor francia ajándékként került New Yorkba.",
  ],
  [
    21,
    "normal",
    "Melyik város ostromához kapcsolódik a mondabeli faló?",
    "Trója",
    "Spárta",
    "Róma",
    "Théba",
    "A trójai faló története a Trója elleni háború mondaköréhez tartozik.",
  ],
  [
    22,
    "hard",
    "Kihez kötődik az egyiptomi hieroglifák megfejtése?",
    "Jean-François Champollion",
    "Heinrich Schliemann",
    "Howard Carter",
    "Arthur Evans",
    "Champollion a rosette-i kő többnyelvű feliratára is támaszkodott.",
  ],
  [
    23,
    "hard",
    "Melyik évben kezdődött az első világháború?",
    "1914",
    "1905",
    "1918",
    "1929",
    "Az első világháború 1914-től 1918-ig tartott.",
  ],
  [
    24,
    "hard",
    "Melyik városban állt az ókor híres, nagy könyvtára?",
    "Alexandria",
    "Karthágó",
    "Spárta",
    "Persepolis",
    "Alexandria a hellenisztikus világ jelentős tudományos központja volt.",
  ],
  [
    25,
    "hard",
    "Melyik uralkodó idején szakadt el az angol egyház a pápai fennhatóságtól?",
    "VIII. Henrik",
    "I. Richárd",
    "I. Vilmos",
    "III. György",
    "VIII. Henrik uralkodása alatt történt az angol egyház elszakadása Rómától.",
  ],
  [
    26,
    "hard",
    "Ki vezette a brit flottát a trafalgari csatában 1805-ben?",
    "Horatio Nelson",
    "Francis Drake",
    "James Cook",
    "Arthur Wellesley",
    "Nelson a csatában életét vesztette, miközben flottája győzelmet aratott.",
  ],
];
