import type { QuestionDraft } from "./types";

// Text-only Hungarian party trivia; review status is tracked centrally.
export const hungaryQuestions: QuestionDraft[] = [
  [
    1,
    "easy",
    "Melyik város Magyarország fővárosa?",
    "Budapest",
    "Debrecen",
    "Szeged",
    "Pécs",
  ],
  [
    2,
    "easy",
    "Melyik Magyarország legnagyobb tava?",
    "Balaton",
    "Velencei-tó",
    "Fertő tó",
    "Tisza-tó",
  ],
  [
    3,
    "easy",
    "Milyen színek szerepelnek a magyar zászlón felülről lefelé?",
    "Piros, fehér, zöld",
    "Zöld, fehér, piros",
    "Piros, zöld, fehér",
    "Fehér, piros, zöld",
  ],
  [
    4,
    "normal",
    "Ki írta a Himnusz szövegét?",
    "Kölcsey Ferenc",
    "Petőfi Sándor",
    "Arany János",
    "Vörösmarty Mihály",
  ],
  [
    5,
    "normal",
    "Melyik Magyarország legmagasabb csúcsa?",
    "Kékes",
    "Dobogó-kő",
    "Írott-kő",
    "Galyatető",
  ],
  [
    6,
    "normal",
    "Ki szerezte a Himnusz zenéjét?",
    "Erkel Ferenc",
    "Liszt Ferenc",
    "Bartók Béla",
    "Kodály Zoltán",
  ],
  [
    7,
    "normal",
    "Melyik városhoz kötődik a Zsolnay Porcelánmanufaktúra?",
    "Pécs",
    "Győr",
    "Eger",
    "Sopron",
  ],
  [
    8,
    "hard",
    "Melyik évben egyesült Pest, Buda és Óbuda Budapestté?",
    "1873",
    "1848",
    "1896",
    "1920",
  ],
  [
    9,
    "hard",
    "Melyik folyó torkollik a Tiszába Szegednél?",
    "Maros",
    "Dráva",
    "Rába",
    "Ipoly",
  ],
  [
    10,
    "hard",
    "Ki kapott 1937-ben orvosi-élettani Nobel-díjat?",
    "Szent-Györgyi Albert",
    "Békésy György",
    "Semmelweis Ignác",
    "Richter Gedeon",
  ],
  [
    11,
    "easy",
    "Melyik folyó választja el Budát és Pestet?",
    "Duna",
    "Tisza",
    "Rába",
    "Körös",
    "Budapest két nagy városrészét a Duna választja el.",
  ],
  [
    12,
    "easy",
    "Melyik magyar ünnepen emlékezünk az 1848-as forradalom kezdetére?",
    "Március 15.",
    "Augusztus 20.",
    "Október 23.",
    "Május 1.",
    "A pesti forradalom eseményeihez március 15-e kapcsolódik.",
  ],
  [
    13,
    "easy",
    "Melyik várost nevezik a hűség városának?",
    "Sopron",
    "Debrecen",
    "Szeged",
    "Győr",
    "Sopronhoz az 1921-es népszavazás nyomán kötődik a cím.",
  ],
  [
    14,
    "easy",
    "Melyik magyar találmány hat oldalán kell egyszínű lapokat kirakni?",
    "Rubik-kocka",
    "Bűvös négyzet",
    "Tangram",
    "Ördöglakat",
    "A klasszikus Rubik-kocka hat lapja különböző színű.",
  ],
  [
    15,
    "easy",
    "Melyik tó partján fekszik Siófok?",
    "Balaton",
    "Velencei-tó",
    "Tisza-tó",
    "Fertő tó",
    "Siófok a Balaton déli partján található.",
  ],
  [
    16,
    "normal",
    "Melyik városban áll a Dóm téren a Fogadalmi templom?",
    "Szeged",
    "Pécs",
    "Eger",
    "Veszprém",
    "A szegedi Fogadalmi templom az árvíz után tett fogadalomhoz kapcsolódik.",
  ],
  [
    17,
    "normal",
    "Ki írta a Nemzeti dalt?",
    "Petőfi Sándor",
    "Arany János",
    "József Attila",
    "Ady Endre",
    "Petőfi verse az 1848-as márciusi események egyik jelképe lett.",
  ],
  [
    18,
    "normal",
    "Melyik magyar tájegységhez kötődik a kilenclyukú híd?",
    "Hortobágy",
    "Őrség",
    "Sárköz",
    "Palócföld",
    "A kilenclyukú híd a Hortobágy folyón ível át.",
  ],
  [
    19,
    "normal",
    "Melyik hegységhez tartozik a Kékes?",
    "Mátra",
    "Bükk",
    "Bakony",
    "Mecsek",
    "A Kékes a Mátra legmagasabb csúcsa.",
  ],
  [
    20,
    "normal",
    "Ki vezette a várvédőket Eger 1552-es ostromakor?",
    "Dobó István",
    "Zrínyi Miklós",
    "Hunyadi János",
    "Kinizsi Pál",
    "Dobó István volt az egri vár kapitánya az 1552-es ostrom idején.",
  ],
  [
    21,
    "normal",
    "Ki volt az első magyar űrhajós?",
    "Farkas Bertalan",
    "Magyari Béla",
    "Bay Zoltán",
    "Simonyi Károly",
    "Farkas Bertalan 1980-ban jutott el az űrbe.",
  ],
  [
    22,
    "hard",
    "Ki írta a Szózat szövegét?",
    "Vörösmarty Mihály",
    "Kölcsey Ferenc",
    "Berzsenyi Dániel",
    "Csokonai Vitéz Mihály",
    "A Szózat Vörösmarty Mihály verse.",
  ],
  [
    23,
    "hard",
    "Melyik építész tervezte az Országházat?",
    "Steindl Imre",
    "Ybl Miklós",
    "Lechner Ödön",
    "Hild József",
    "A magyar Országház Steindl Imre tervei alapján épült.",
  ],
  [
    24,
    "hard",
    "Melyik magyar városban található az Eszterházy Károly nevéhez kötődő Líceum?",
    "Eger",
    "Vác",
    "Sopron",
    "Kaposvár",
    "Az egri Líceumot Eszterházy Károly püspök alapította.",
  ],
  [
    25,
    "hard",
    "Melyik országot köti össze Magyarországgal a Mária Valéria híd?",
    "Szlovákia",
    "Ausztria",
    "Horvátország",
    "Szlovénia",
    "A híd Esztergomot és Párkányt köti össze.",
  ],
  [
    26,
    "hard",
    "Ki alkotta a Magyar rapszódiák zongoradarab-sorozatát?",
    "Liszt Ferenc",
    "Erkel Ferenc",
    "Kodály Zoltán",
    "Dohnányi Ernő",
    "Liszt Magyar rapszódiái zongorára írt művek.",
  ],
];
