import type { QuestionDraft } from "./types";

// Text-only Hungarian party trivia; review status is tracked centrally.
export const mixedQuestions: QuestionDraft[] = [
  [
    1,
    "easy",
    "Hány oldala van egy háromszögnek?",
    "Három",
    "Négy",
    "Öt",
    "Hat",
  ],
  [
    2,
    "easy",
    "Hány perc van egy órában?",
    "Hatvan",
    "Harminc",
    "Kilencven",
    "Száz",
  ],
  [
    3,
    "easy",
    "Melyik égtáj felé mutat az iránytű északi vége?",
    "Mágneses észak felé",
    "Mindig kelet felé",
    "Mindig dél felé",
    "Mindig nyugat felé",
  ],
  [4, "normal", "Melyik római szám jelöli az ötvenet?", "L", "X", "C", "D"],
  [
    5,
    "normal",
    "Hány mezőből áll egy szabályos sakktábla?",
    "Hatvannégy",
    "Ötvenhat",
    "Hetvenkettő",
    "Nyolcvanegy",
  ],
  [
    6,
    "normal",
    "Milyen írásrendszerben használják a Braille-pontokat?",
    "Tapintással olvasható írás",
    "Gyorsírás",
    "Morzekód",
    "Hieroglif írás",
  ],
  [
    7,
    "normal",
    "Melyik geometriai alakzatnak nincs sarka?",
    "Kör",
    "Négyzet",
    "Háromszög",
    "Trapéz",
  ],
  [
    8,
    "hard",
    "Melyik SI-előtag jelent egymilliomod részt?",
    "Mikro",
    "Milli",
    "Nano",
    "Kilo",
  ],
  [
    9,
    "hard",
    "Hány fok a hatszög belső szögeinek összege?",
    "720",
    "540",
    "360",
    "900",
  ],
  [
    10,
    "hard",
    "Melyik SI-előtag jelent 10¹²-szeres szorzót?",
    "Tera",
    "Giga",
    "Mega",
    "Peta",
  ],
  [
    11,
    "easy",
    "Hány napból áll egy hét?",
    "Hét",
    "Öt",
    "Hat",
    "Nyolc",
    "A hét napjai hét egymást követő napot alkotnak.",
  ],
  [
    12,
    "easy",
    "Melyik eszköz mutatja hagyományosan az időt mutatókkal?",
    "Óra",
    "Hőmérő",
    "Barométer",
    "Iránytű",
    "Az analóg óra mutatói az órát és a percet jelzik.",
  ],
  [
    13,
    "easy",
    "Hány lapja van a hagyományos kocka alakú dobótestnek?",
    "Hat",
    "Négy",
    "Nyolc",
    "Tizenkettő",
    "A kockának hat négyzet alakú lapja van.",
  ],
  [
    14,
    "easy",
    "Melyik nap követi a csütörtököt?",
    "Péntek",
    "Szerda",
    "Szombat",
    "Vasárnap",
    "A hét sorrendjében csütörtök után péntek következik.",
  ],
  [
    15,
    "easy",
    "Melyik szín jelzi a közúti jelzőlámpán a szabad utat?",
    "Zöld",
    "Piros",
    "Sárga",
    "Kék",
    "A zöld jelzés továbbhaladást enged, a közlekedési szabályok betartásával.",
  ],
  [
    16,
    "normal",
    "Hány fokos a derékszög?",
    "90",
    "45",
    "120",
    "180",
    "A derékszög a teljes fordulat negyede.",
  ],
  [
    17,
    "normal",
    "Mennyi egy tucat darab?",
    "Tizenkettő",
    "Tíz",
    "Húsz",
    "Huszonnégy",
    "A tucat tizenkét egységet jelent.",
  ],
  [
    18,
    "normal",
    "Melyik mértékegységben adunk meg gyakran folyadéktérfogatot?",
    "Liter",
    "Méter",
    "Kilogramm",
    "Másodperc",
    "A liter térfogatmértékegység, nem tömeg- vagy hosszegység.",
  ],
  [
    19,
    "normal",
    "Melyik égtáj van észak és kelet között félúton?",
    "Északkelet",
    "Délkelet",
    "Északnyugat",
    "Délnyugat",
    "Az északkelet két szomszédos fő égtáj közötti mellékégtáj.",
  ],
  [
    20,
    "normal",
    "Mit jelent a WWW rövidítés?",
    "World Wide Web",
    "World Wireless Wave",
    "Wide Windows Work",
    "Web With Words",
    "A World Wide Web a világhálót jelenti.",
  ],
  [
    21,
    "normal",
    "Melyik eszköz méri a légnyomást?",
    "Barométer",
    "Higrométer",
    "Anemométer",
    "Luxmérő",
    "A barométer nyomást mér; a többi eszköz más fizikai mennyiségre szolgál.",
  ],
  [
    22,
    "hard",
    "Melyik szám prímszám?",
    "29",
    "21",
    "27",
    "33",
    "A 29 csak eggyel és önmagával osztható pozitív egész számmal.",
  ],
  [
    23,
    "hard",
    "Hány él találkozik egy kocka minden csúcsában?",
    "Három",
    "Kettő",
    "Négy",
    "Hat",
    "Egy kocka csúcsán három egymásra merőleges él találkozik.",
  ],
  [
    24,
    "hard",
    "Hány fok a szabályos ötszög egy belső szöge?",
    "108",
    "90",
    "120",
    "135",
    "Az ötszög szögösszege 540 fok, ez szabályos esetben öt egyenlő részre oszlik.",
  ],
  [
    25,
    "hard",
    "Melyik római szám jelöli a kilencszázat?",
    "CM",
    "CD",
    "XC",
    "DCCCCX",
    "A CM a kivonásos római jelölés szerint 1000 mínusz 100.",
  ],
  [
    26,
    "hard",
    "Melyik SI-előtag jelent egymilliárdod részt?",
    "Nano",
    "Mikro",
    "Milli",
    "Piko",
    "A nano előtag 10⁻⁹-szeres szorzót jelent.",
  ],
];
