import type { QuestionDraft } from "./types";

// Text-only Hungarian party trivia; review status is tracked centrally.
export const musicQuestions: QuestionDraft[] = [
  [
    1,
    "easy",
    "Hány húrja van egy szokásos gitárnak?",
    "Hat",
    "Négy",
    "Nyolc",
    "Tizenkettő",
  ],
  [
    2,
    "easy",
    "Melyik zenekar tagja volt Freddie Mercury?",
    "Queen",
    "The Beatles",
    "ABBA",
    "Nirvana",
  ],
  [
    3,
    "easy",
    "Melyik hangszernek vannak fekete és fehér billentyűi?",
    "Zongora",
    "Hegedű",
    "Trombita",
    "Dob",
  ],
  [
    4,
    "normal",
    "Melyik városból indult a Beatles?",
    "Liverpool",
    "London",
    "Manchester",
    "Glasgow",
  ],
  [
    5,
    "normal",
    "Ki komponálta A varázsfuvolát?",
    "Wolfgang Amadeus Mozart",
    "Ludwig van Beethoven",
    "Johann Sebastian Bach",
    "Giuseppe Verdi",
  ],
  [
    6,
    "normal",
    "Melyik országból származik az ABBA?",
    "Svédország",
    "Norvégia",
    "Dánia",
    "Finnország",
  ],
  [
    7,
    "normal",
    "Melyik kulcsot használják leggyakrabban a hegedű szólamához?",
    "Violinkulcs",
    "Basszuskulcs",
    "Altkulcs",
    "Tenorkulcs",
  ],
  [
    8,
    "normal",
    "Ki komponálta a Négy évszak hegedűversenyeket?",
    "Antonio Vivaldi",
    "Frédéric Chopin",
    "Richard Wagner",
    "Claude Debussy",
  ],
  [
    9,
    "normal",
    "Melyik ütemmutató jellemző a klasszikus keringőre?",
    "3/4",
    "4/4",
    "2/4",
    "5/4",
  ],
  [
    10,
    "hard",
    "Hány félhangból áll egy tiszta oktáv?",
    "Tizenkettő",
    "Hét",
    "Nyolc",
    "Tíz",
  ],
  [
    11,
    "easy",
    "Melyik hangszer szólal meg elsősorban a húrok vonóval való megszólaltatásával?",
    "Hegedű",
    "Fuvola",
    "Trombita",
    "Klarinét",
    "A hegedű húrait rendszerint vonóval szólaltatják meg.",
  ],
  [
    12,
    "easy",
    "Milyen hangszercsoportba tartozik a trombita?",
    "Rézfúvós",
    "Vonós",
    "Ütős",
    "Billentyűs",
    "A trombita rézfúvós hangszer, hangját a rezgő ajkak keltik.",
  ],
  [
    13,
    "easy",
    "Ki kapta a pop királya becenevet?",
    "Michael Jackson",
    "Elvis Presley",
    "Prince",
    "David Bowie",
    "Michael Jacksont nevezték a pop királyának.",
  ],
  [
    14,
    "easy",
    "Melyik együttes slágere a Dancing Queen?",
    "ABBA",
    "Queen",
    "Boney M.",
    "Bee Gees",
    "A Dancing Queen az ABBA egyik legismertebb dala.",
  ],
  [
    15,
    "easy",
    "Melyik hangszer használ pedálokat és nagy, függőleges húrsort?",
    "Koncerthárfa",
    "Mandolin",
    "Ukulele",
    "Bendzsó",
    "A koncerthárfa pedáljai a húrok hangmagasságát módosítják.",
  ],
  [
    16,
    "normal",
    "Mit jelent az olasz „piano” utasítás a kottában?",
    "Halkan",
    "Gyorsan",
    "Nagyon lassan",
    "Erősen hangsúlyozva",
    "A piano dinamikai jelzés, nem tempómegadás.",
  ],
  [
    17,
    "normal",
    "Hány húrja van egy szokásos ukulelének?",
    "Négy",
    "Hat",
    "Hét",
    "Tizenkettő",
    "A hagyományos ukulelén négy húr található.",
  ],
  [
    18,
    "normal",
    "Melyik zenekarhoz kötődik a Smells Like Teen Spirit?",
    "Nirvana",
    "Metallica",
    "Oasis",
    "Radiohead",
    "A dal a Nirvana Nevermind albumán jelent meg.",
  ],
  [
    19,
    "normal",
    "Melyik országban született Frédéric Chopin?",
    "Lengyelország",
    "Franciaország",
    "Ausztria",
    "Olaszország",
    "Chopin Lengyelországban született, később Párizsban élt.",
  ],
  [
    20,
    "normal",
    "Milyen hangmagasságot jelöl a nemzetközi jelölésben a 440 Hz-es hang?",
    "A",
    "C",
    "E",
    "G",
    "A 440 Hz általában az egyvonalas a hang hangolási referenciaértéke.",
  ],
  [
    21,
    "normal",
    "Melyik magyar zeneszerzőhöz kötődik A kékszakállú herceg vára?",
    "Bartók Béla",
    "Kodály Zoltán",
    "Erkel Ferenc",
    "Liszt Ferenc",
    "Bartók operájának szövegkönyvét Balázs Béla írta.",
  ],
  [
    22,
    "hard",
    "Melyik zeneszerző írta a Magyar táncok sorozatát?",
    "Johannes Brahms",
    "Liszt Ferenc",
    "Antonín Dvořák",
    "Edvard Grieg",
    "Brahms Magyar táncai magyaros táncdallamokra épülnek.",
  ],
  [
    23,
    "hard",
    "Melyik együttes adta ki a The Dark Side of the Moon albumot 1973-ban?",
    "Pink Floyd",
    "Led Zeppelin",
    "Deep Purple",
    "Black Sabbath",
    "Az album a Pink Floyd legismertebb lemezei közé tartozik.",
  ],
  [
    24,
    "hard",
    "Melyik előadó albumán található a Ziggy Stardust alakjához kötődő történet?",
    "David Bowie",
    "Elton John",
    "Freddie Mercury",
    "Paul McCartney",
    "Bowie a Ziggy Stardust lemezen egy kitalált rocksztár figuráját alkotta meg.",
  ],
  [
    25,
    "hard",
    "Melyik zeneszerző Kilencedik szimfóniájának része az Örömóda?",
    "Ludwig van Beethoven",
    "Wolfgang Amadeus Mozart",
    "Joseph Haydn",
    "Franz Schubert",
    "Beethoven szimfóniájának zárótétele Schiller Örömódáját dolgozza fel.",
  ],
  [
    26,
    "hard",
    "Melyik tempójelzés jelent általában gyors, élénk előadást?",
    "Allegro",
    "Largo",
    "Adagio",
    "Grave",
    "Az allegro tempójelzés gyors, élénk játékmódot kér.",
  ],
];
