import type { QuestionDraft } from "./types";

// Text-only Hungarian party trivia; review status is tracked centrally.
export const scienceQuestions: QuestionDraft[] = [
  [1, "easy", "Mi a víz kémiai képlete?", "H₂O", "CO₂", "O₂", "NaCl"],
  [
    2,
    "easy",
    "Melyik bolygót nevezik vörös bolygónak?",
    "Mars",
    "Vénusz",
    "Jupiter",
    "Merkúr",
  ],
  [3, "easy", "Melyik szerv pumpálja a vért?", "Szív", "Tüdő", "Máj", "Vese"],
  [4, "normal", "Mi a vas vegyjele?", "Fe", "Au", "Ag", "Cu"],
  [
    5,
    "normal",
    "Melyik bolygó a Naprendszer legnagyobb bolygója?",
    "Jupiter",
    "Szaturnusz",
    "Neptunusz",
    "Föld",
  ],
  [
    6,
    "normal",
    "Mi a növények fényenergiát hasznosító, cukrot előállító folyamatának neve?",
    "Fotoszintézis",
    "Párolgás",
    "Erjedés",
    "Lepárlás",
  ],
  [
    7,
    "normal",
    "Melyik részecske hordoz negatív elektromos töltést?",
    "Elektron",
    "Proton",
    "Neutron",
    "Foton",
  ],
  [
    8,
    "hard",
    "Mi az elektromos ellenállás SI-mértékegysége?",
    "Ohm",
    "Volt",
    "Amper",
    "Watt",
  ],
  [
    9,
    "hard",
    "Melyik szerv termeli az inzulint?",
    "Hasnyálmirigy",
    "Lép",
    "Epehólyag",
    "Pajzsmirigy",
  ],
  [
    10,
    "hard",
    "Melyik fizikai mennyiség SI-mértékegysége a pascal?",
    "Nyomás",
    "Energia",
    "Teljesítmény",
    "Elektromos töltés",
  ],
  [
    11,
    "easy",
    "Melyik érzékszervünkkel hallunk?",
    "Fül",
    "Szem",
    "Orr",
    "Nyelv",
    "A fül a hallás érzékszerve, és az egyensúlyozásban is részt vesz.",
  ],
  [
    12,
    "easy",
    "Milyen állapotú a víz jég formájában?",
    "Szilárd",
    "Folyékony",
    "Légnemű",
    "Plazma",
    "A jég a víz szilárd halmazállapota.",
  ],
  [
    13,
    "easy",
    "Melyik csillag körül kering a Föld?",
    "Nap",
    "Sarkcsillag",
    "Szíriusz",
    "Vega",
    "A Föld a Naprendszer egyik bolygója.",
  ],
  [
    14,
    "easy",
    "Melyik testrész védi csontosan az agyat?",
    "Koponya",
    "Medence",
    "Bordakosár",
    "Lapocka",
    "A koponya csontjai körülveszik és védik az agyat.",
  ],
  [
    15,
    "easy",
    "Milyen erő tartja a Föld közelében a leejtett tárgyakat?",
    "Gravitáció",
    "Mágneses erő",
    "Súrlódási erő",
    "Felületi feszültség",
    "A Föld tömegvonzása a tárgyakat a bolygó felé gyorsítja.",
  ],
  [
    16,
    "normal",
    "Miért úszik a jég a folyékony víz tetején?",
    "Kisebb a sűrűsége",
    "Nagyobb a sűrűsége",
    "Nem hat rá gravitáció",
    "Elektromosan taszítja a vizet",
    "A jég szerkezete miatt kevésbé sűrű, mint a folyékony víz.",
  ],
  [
    17,
    "normal",
    "Milyen egységben mérjük az elektromos áramerősséget?",
    "Amper",
    "Volt",
    "Ohm",
    "Watt",
    "Az áramerősség SI-mértékegysége az amper.",
  ],
  [
    18,
    "normal",
    "Melyik gázból van a legtöbb a száraz földi légkörben?",
    "Nitrogén",
    "Oxigén",
    "Szén-dioxid",
    "Argon",
    "A száraz levegő térfogatának nagyjából 78 százaléka nitrogén.",
  ],
  [
    19,
    "normal",
    "Hogyan nevezzük a folyadék gázállapotba kerülését a felszínén?",
    "Párolgás",
    "Olvadás",
    "Fagyás",
    "Lecsapódás",
    "Párolgáskor a felszínről távoznak a folyadék részecskéi.",
  ],
  [
    20,
    "normal",
    "Milyen töltésű a proton?",
    "Pozitív",
    "Negatív",
    "Semleges",
    "Mindig változó",
    "A proton pozitív töltését az elektron azonos nagyságú negatív töltése ellensúlyozhatja.",
  ],
  [
    21,
    "normal",
    "Melyik szervünk fő feladata a vér szűrése és a vizelet képzése?",
    "Vese",
    "Gyomor",
    "Lép",
    "Epehólyag",
    "A vesék szabályozzák a víz- és sóháztartást, és vizeletet képeznek.",
  ],
  [
    22,
    "hard",
    "Mik a fehérjék láncait felépítő alapegységek?",
    "Aminosavak",
    "Zsírsavak",
    "Egyszerű cukrok",
    "Nukleotidok",
    "A fehérjéket egymáshoz kapcsolódó aminosavak alkotják.",
  ],
  [
    23,
    "hard",
    "Mi a DNS teljes magyar neve?",
    "Dezoxiribonukleinsav",
    "Ribonukleinsav",
    "Adenozin-trifoszfát",
    "Dezoxiribóz-foszfát",
    "A DNS neve a dezoxiribonukleinsav rövidítése.",
  ],
  [
    24,
    "hard",
    "Mit mér a hertz nevű mértékegység?",
    "Frekvenciát",
    "Nyomást",
    "Energiát",
    "Elektromos ellenállást",
    "Egy hertz másodpercenként egy ismétlődést jelent.",
  ],
  [
    25,
    "hard",
    "Melyik bolygó forog az oldalára billent tengellyel?",
    "Uránusz",
    "Jupiter",
    "Mars",
    "Merkúr",
    "Az Uránusz forgástengelyének dőlése megközelíti a 98 fokot.",
  ],
  [
    26,
    "hard",
    "Melyik részecskék találhatók az atommagban a szokásos atommodell szerint?",
    "Protonok és neutronok",
    "Elektronok és fotonok",
    "Csak elektronok",
    "Protonok és elektronok",
    "Az atommag protonokat tartalmaz, és a hidrogén leggyakoribb izotópját kivéve neutronokat is.",
  ],
];
