import type { QuestionDraft } from "./types";

// Text-only Hungarian party trivia; review status is tracked centrally.
export const sportQuestions: QuestionDraft[] = [
  [
    1,
    "easy",
    "Hány játékos van egy labdarúgócsapatban a pályán a mérkőzés kezdetén?",
    "Tizenegy",
    "Kilenc",
    "Hét",
    "Tizenhárom",
  ],
  [
    2,
    "easy",
    "Melyik sporthoz tartozik a kosárra dobás?",
    "Kosárlabda",
    "Kézilabda",
    "Rögbi",
    "Röplabda",
  ],
  [
    3,
    "easy",
    "Melyik ütős sport labdájának van tollból vagy műanyagból készült szoknyája?",
    "Tollaslabda",
    "Tenisz",
    "Squash",
    "Asztalitenisz",
  ],
  [
    4,
    "normal",
    "Milyen hosszú a maratoni futóverseny hivatalos távja?",
    "42,195 km",
    "40 km",
    "21,0975 km",
    "50 km",
  ],
  [
    5,
    "normal",
    "Hány karika szerepel az olimpiai jelképen?",
    "Öt",
    "Négy",
    "Hat",
    "Hét",
  ],
  [
    6,
    "normal",
    "Melyik Grand Slam tenisztornát játsszák füvön?",
    "Wimbledon",
    "Roland Garros",
    "US Open",
    "Australian Open",
  ],
  [
    7,
    "easy",
    "Melyik országban rendezik a Tour de France nagy részét?",
    "Franciaország",
    "Spanyolország",
    "Olaszország",
    "Belgium",
  ],
  [
    8,
    "easy",
    "Melyik sakkfigura lép L alakban?",
    "Huszár",
    "Futó",
    "Bástya",
    "Vezér",
  ],
  [
    9,
    "normal",
    "Hány játékos van egy röplabdacsapatban egyszerre a pályán a szabályos teremröplabdában?",
    "Hat",
    "Öt",
    "Hét",
    "Nyolc",
  ],
  [
    10,
    "hard",
    "Melyik úszásnemben kötelező a vízből egyszerre előrevinni mindkét kart?",
    "Pillangóúszás",
    "Gyorsúszás",
    "Hátúszás",
    "Mellúszás",
  ],
  [
    11,
    "easy",
    "Melyik sportban használják a kapus és hetes kifejezéseket az alábbiak közül?",
    "Kézilabda",
    "Röplabda",
    "Tenisz",
    "Vívás",
    "Kézilabdában a büntetődobást a hétméteres vonalról végzik el.",
  ],
  [
    12,
    "easy",
    "Melyik sportban kell a labdát minél kevesebb ütéssel egy lyukba juttatni?",
    "Golf",
    "Krikett",
    "Baseball",
    "Gyeplabda",
    "A golfban a pálya lyukait minél kevesebb ütéssel kell teljesíteni.",
  ],
  [
    13,
    "easy",
    "Hány bábu áll a pálya végén a bowling legelterjedtebb változatában?",
    "Tíz",
    "Kilenc",
    "Hat",
    "Tizenkettő",
    "A bábuk tízes csoportban, háromszög alakzatban állnak.",
  ],
  [
    14,
    "easy",
    "Melyik sporthoz tartozik a szlalom versenyszám az alábbiak közül?",
    "Alpesi sí",
    "Gyorskorcsolya",
    "Síugrás",
    "Curling",
    "Az alpesi sí szlalompályáján kapuk között kell lesiklani.",
  ],
  [
    15,
    "easy",
    "Melyik sportban használják a jab és az uppercut ütéseket?",
    "Ökölvívás",
    "Vívás",
    "Birkózás",
    "Cselgáncs",
    "Ezek az ökölvívás jellegzetes ütéstípusai.",
  ],
  [
    16,
    "normal",
    "Hány pontot ér egy szabályos büntetődobás kosárlabdában?",
    "Egy",
    "Kettő",
    "Három",
    "Négy",
    "A kosárlabda büntetődobása egy pontot ér.",
  ],
  [
    17,
    "normal",
    "Hány ponttal kezdődik egy hagyományos 501-es dartsleg?",
    "501",
    "301",
    "401",
    "601",
    "A játékosok 501 pontról indulnak, és nullára próbálnak jutni.",
  ],
  [
    18,
    "normal",
    "Melyik sportban használják a „love” szót a nulla pontra?",
    "Tenisz",
    "Rögbi",
    "Jégkorong",
    "Baseball",
    "A tenisz pontbemondásában a love jelenti a nullát.",
  ],
  [
    19,
    "normal",
    "Melyik sportban található ugrás, felemás korlát, gerenda és talaj a női összetettben?",
    "Torna",
    "Ritmikus gimnasztika",
    "Műugrás",
    "Öttusa",
    "A női szertorna összetett versenye négy szerből áll.",
  ],
  [
    20,
    "normal",
    "Hány mezőn áll egy-egy játékos gyalogsora a sakk kezdőállásában?",
    "Nyolc",
    "Hat",
    "Tíz",
    "Tizenkettő",
    "Mindkét játékos nyolc gyaloggal kezdi a partit.",
  ],
  [
    21,
    "normal",
    "Melyik sportban ül a játékos általában két percet a büntetőpadon kisbüntetésnél?",
    "Jégkorong",
    "Tenisz",
    "Golf",
    "Tollaslabda",
    "A jégkorong kisbüntetése általában két perc, de emberelőnyös gól esetén korábban is véget érhet.",
  ],
  [
    22,
    "hard",
    "Melyik olimpiai dobószámban használnak nyeles, dróton függő súlygolyót?",
    "Kalapácsvetés",
    "Súlylökés",
    "Gerelyhajítás",
    "Diszkoszvetés",
    "A kalapácsvetés eszköze fogantyúból, drótból és fémgolyóból áll.",
  ],
  [
    23,
    "hard",
    "Melyik színű trikót viseli a Tour de France összetett éllovasa?",
    "Sárga",
    "Zöld",
    "Fehér",
    "Piros pöttyös",
    "A sárga trikó az összetett időverseny vezetőjét jelöli.",
  ],
  [
    24,
    "hard",
    "Melyik sportban része a pontozásnak a waza-ari?",
    "Cselgáncs",
    "Szumó",
    "Taekwondo",
    "Ökölvívás",
    "A waza-ari a cselgáncs pontértékei közé tartozik.",
  ],
  [
    25,
    "hard",
    "Melyik sport szabályai szerint ér öt pontot egy cél?",
    "Rögbiunió",
    "Amerikai futball",
    "Rögbiligás játék",
    "Ausztrál futball",
    "A rögbiunióban a cél öt pontot ér; az utána járó jutalomrúgás külön pontokat hozhat.",
  ],
  [
    26,
    "hard",
    "Melyik vívófegyvernél érvényes találati felület az egész test?",
    "Párbajtőr",
    "Tőr",
    "Kard",
    "Mindháromnál",
    "Párbajtőrvívásban az egész test találati felület.",
  ],
];
